### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by zjuchenyuan** [Light-It-Up-Game/Light-It-Up#1]
Release1.8.1版本中
第三关 电容器
“将电容器与灯泡连接，电容器放点”
放点→放电

**Comment by xjiajiahao** [comment]
Thanks for your feedback. This issuse has been fixed in source code.

**Comment by zjuchenyuan** [comment]
Why not make a new release?
I don't know how to compile it...

**Comment by xjiajiahao** [comment]
I'm so sorry but recently I'm too busy to compile and release a new version with [Cocos Creator](http://www.cocos.com/creator), which is time-consuming. Maybe I will have time to do so after the finals.
